name: "Publish Amazon S3 Backup"

on:
  push:
    branches: [ "main" ]

jobs:
  publish:
    name: Publish Amazon S3 Backup Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.1.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Check Version
        id: check
        uses: ./.github/actions/check-ghcr
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          image: wozz/ha-addons/amazon-s3-backup-aarch64
          configpath: amazon-s3-backup/config.json
      - name: Publish
        if: ${{ steps.check.outputs.status == '404' }}
        uses: home-assistant/builder@master
        with:
          args: |
            --all \
            --target amazon-s3-backup \
            --docker-hub ghcr.io/wozz/ha-addons \
            --image amazon-s3-backup-{arch}
