name: "Publish Logspout"

on:
  push:
    branches: [ "main" ]

jobs:
  publish:
    name: Publish Logspout Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Check Version
        id: check
        uses: ./.github/actions/check-ghcr
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          image: wozz/ha-addons/logspout-aarch64
          configpath: logspout/config.yaml
      - name: Publish
        if: ${{ steps.check.outputs.status == '404' }}
        uses: home-assistant/builder@master
        with:
          args: |
            --aarch64 --amd64 \
            --target logspout \
            --docker-hub ghcr.io/wozz/ha-addons \
            --image logspout-{arch}
